apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: tf-serving-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: tf-serving-deployment
  updatePolicy:
    updateMode: "Off"
